language: node_js
before_script:
- npm install -g istanbul
- npm install -g mocha
- npm install -g coveralls
node_js:
- stable
install:
- npm install
script: ./node_modules/.bin/eslint ./src/VideoFrame.js
script: 'npm run coverage'
after_success: 'npm run coveralls'
